name = "PhyloTrees"
uuid = "4c47b132-0681-5a5d-b498-3afcf53fd314"
authors = ["Justin Angevaare <justinangevaare@gmail.com>"]
version = "0.11.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "^1"
julia = "1, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
